# Site settings
title: Will Gallop's Site
email: wgallop99@gmail.com
url: "http://willgallop.me" # the base hostname & protocol for your site
twitter_username: wgallop99
paginate: 2

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Will Gallop
      layout: "post"
      category: example
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"



# Gems
gems:  [jekyll-paginate]

